title: <p align="center"> Chaithanya V </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://github.com/cveluru">GitHub</a>

  <br>
  I'm working on Data Science, Machine learning & NLP related problems.
  <br>
  </p>



theme: jekyll-theme-minimal
